local f00lskidd = {
    SchemeColor = Color3.fromRGB(10,143,0),
    Background = Color3.fromRGB(0, 0, 0),
    Header = Color3.fromRGB(0, 0, 0),
    TextColor = Color3.fromRGB(255,255,255),
    ElementColor = Color3.fromRGB(20, 20, 20)
}
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("f00lskidd gui", f00lskidd)
local Tab = Window:NewTab("Pr0nK")
local Section = Tab:NewSection("Scripts")
Section:NewButton("Ant1 AFK", "none", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FantZarYT/f00lskidd-gui/main/antiafk.lua")()
end)
Section:NewButton("Remote Spy", "none", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/bCghX33W", true))()
end)
Section:NewButton("f00lye3t gui", "none", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FantZarYT/f00lskidd-gui/main/f00lye3t%20gui.lua", true))() 
end)
Section:NewButton("Dark Dex v3", "none", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Babyhamsta/RBLX_Scripts/main/Universal/BypassedDarkDexV3.lua", true))()
end)
Section:NewButton("Infinite Yield", "none", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))() 
end)
Section:NewButton("Dance Fl1ng (R6)", "none", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FantZarYT/f00lskidd-gui/main/dance%20fling.lua", true))() 
end)
Section:NewButton("S3x (R6)", "none", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FantZarYT/f00lskidd-gui/main/tr0ll%20xd.lua"))()
end)
Section:NewButton("Invis Fling (R6)", "none", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FantZarYT/f00lskidd-gui/main/invisfling.lua"))()
end)
Section:NewButton("Animation Changer", "none", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FantZarYT/f00lskidd-gui/main/Anim%20Changer.lua"))()
end)
Section:NewButton("Midi Player (For Piano)", "none", function()
    loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/richie0866/MidiPlayer/main/package.lua"))()
end)
Section:NewButton("Lag Server", "none", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/yGqP4zFa"))()
end)
local Tab = Window:NewTab("All Gam3s")
local Section = Tab:NewSection("External")
Section:NewButton("ESP + Aim Gui", "none", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Exunys/AirHub/main/AirHub.lua"))()
end)
local Tab = Window:NewTab("Credits")
local Section = Tab:NewSection("Thank You!")
local Section = Tab:NewSection("Source By Kavo UI")
local Section = Tab:NewSection("Script's Founded By 3181#6962")
local Section = Tab:NewSection("For Idea this Script By FORGET#8726")
local Sectiom = Tab:NewSection("Thank you for using this script")
local Sectiom = Tab:NewSection("                          :D")
end)
